# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Print the date in `n` days from now
#' @export
dateInDays <- function(n) {
    .Call('_RQuantLibExample_dateInDays', PACKAGE = 'RQuantLibExample', n)
}

#' @export
yearFrac <- function(date1, date2) {
    .Call('_RQuantLibExample_yearFrac', PACKAGE = 'RQuantLibExample', date1, date2)
}

#' @export
couponDates <- function(start, maturity, freq) {
    .Call('_RQuantLibExample_couponDates', PACKAGE = 'RQuantLibExample', start, maturity, freq)
}

#' @export
daysBetween <- function(dates) {
    .Call('_RQuantLibExample_daysBetween', PACKAGE = 'RQuantLibExample', dates)
}

